---
services:
  runner:
    image: docker-gh-runner-linux:latest
    build:
      context: .
      args:
        RUNNER_VERSION: '2.317.0'
    environment:
      # Set the values under ~/.env file
      GH_TOKEN: ${GH_TOKEN}
      GH_OWNER: ${GH_OWNER}
      GH_REPOSITORY: ${GH_REPOSITORY}
