---
version: '3.8'

services:
  runner:
    image: docker-gh-runner-linux:latest
    build:
      context: .
      args:
        RUNNER_VERSION: '2.317.0'
        RUNNER_HASH: '9e883d210df8c6028aff475475a457d380353f9d01877d51cc01a17b2a91161d'
    environment:
      GH_TOKEN: ${GH_TOKEN}
      GH_OWNER: ${GH_OWNER}
      GH_REPOSITORY: ${GH_REPOSITORY}
